name: "oidc-setup"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: "Run Terraform OIDC Setup"
    runs-on: ubuntu-latest
    environment: terraform-deploy
    permissions:
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./oidc

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: github.event.inputs.action != 'destroy'
        run: terraform plan -no-color -input=false -out oidcplan

      - name: Terraform apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -input=false oidcplan

      - name: Terraform destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -input=false